POST http://localhost:3003/users
content-type: application/json

{
    "name": "Astrodev",
    "email": "astrodev@mail.com",
    "password": "1234567"
}

###

GET http://localhost:3003/users

###

POST http://localhost:3003/products
content-type: application/json

{
    "name": "Viagem de balão",
    "price": 289.90,
    "imageUrl": "https://i.picsum.photos/id/174/1600/589.jpg?hmac=W4bG4rAGyrN9dOGFpK_BB6yROybLRgCsKQErTl9llRQ"
}

###

GET http://localhost:3003/products

###

POST http://localhost:3003/purchases
content-type: application/json

{
    "userId": "16620629124920.7650680293111722",
    "productId": "16621557810960.7699760064375643",
    "quantity": 3
}

###

GET http://localhost:3003/users/16620629124920.7650680293111722/purchases

###