GET http://localhost:3003/user

###

GET http://localhost:3003/user?name=soter

###

GET http://localhost:3003/user/teacher

###

GET http://localhost:3003/user/order

###

GET http://localhost:3003/user/page?page=4