GET http://localhost:3003/pets

###

POST http://localhost:3003/dog_walking/create
Content-Type: application/json

{
    "date": "12/10/2022",
    "latitude": 90,
    "longitude": -22,
    "startTime": "12:00",
    "finishTime": "13:00",
    "pets": [
        "91950e5f-f4e0-434f-b113-3c3fcc29ca8b",
        "18b5ab95-6194-46ec-ba6d-5f263a340f29"
    ]
}

###