POST http://localhost:3003/signup
content-type: application/json

{
    "name": "Dan",
    "email": "dan@email.com",
    "password": "1234567"
}

###

POST http://localhost:3003/login
content-type: application/json

{
    "email": "dan@email.com",
    "password": "1234567"
}

###